Repository kubermatic/kubecarrier, pull requests merged in 2020-07, with the labels that each got.

#497 add `paused` flag to catapult
  config/operator/crd/bases/operator.kubecarrier.io_catapults.yaml
  pkg/apis/operator/v1alpha1/catapult_types.go
  pkg/apiserver/api/v1/validation.go
  pkg/internal/resources/operator/operator.golden.yaml
  pkg/internal/resources/operator/statik.go
  pkg/manager/internal/controllers/customresourcediscovery_controller.go
  pkg/operator/internal/controllers/catapult_controller.go
  test/integration/servicecluster.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#501 added boilerplate binary to test.Dockerfile
  config/dockerfiles/test.Dockerfile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#502 Add paused flag
  config/operator/crd/bases/operator.kubecarrier.io_elevators.yaml
  config/operator/crd/bases/operator.kubecarrier.io_ferries.yaml
  config/operator/crd/bases/operator.kubecarrier.io_kubecarriers.yaml
  pkg/apis/operator/v1alpha1/catapult_types.go
  pkg/apis/operator/v1alpha1/elevator_types.go
  pkg/apis/operator/v1alpha1/ferry_types.go
  pkg/apis/operator/v1alpha1/kubecarrier_types.go
  pkg/apis/operator/v1alpha1/types.go
  pkg/internal/resources/operator/operator.golden.yaml
  pkg/internal/resources/operator/statik.go
  pkg/manager/internal/controllers/derivedcustomresource_controller.go
  pkg/manager/internal/controllers/servicecluster_controller.go
  pkg/operator/internal/controllers/elevator_controller.go
  pkg/operator/internal/controllers/ferry_controller.go
  pkg/operator/internal/controllers/kubecarrier_controller.go
  test/integration/derivedcr.go
  test/integration/servicecluster.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#499 add auth schema with auth providers order
  config/operator/crd/bases/operator.kubecarrier.io_apiservers.yaml
  config/operator/crd/bases/operator.kubecarrier.io_kubecarriers.yaml
  config/operator/default/webhookcainjection_patch.yaml
  config/operator/webhook/manifests.yaml
  pkg/apis/operator/v1alpha1/apiserver_types.go
  pkg/apis/operator/v1alpha1/kubecarrier_types_test.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/apiserver/auth/auth.go
  pkg/apiserver/internal/auth/anonymous/anonymous.go
  pkg/apiserver/internal/auth/htpasswd/htpasswd.go
  pkg/apiserver/internal/auth/oidc/oidc.go
  pkg/apiserver/internal/auth/token/token.go
  pkg/internal/resources/apiserver/apiserver.go
  pkg/internal/resources/apiserver/apiserver.golden.yaml
  pkg/internal/resources/apiserver/apiserver_test.go
  pkg/internal/resources/operator/operator.golden.yaml
  pkg/internal/resources/operator/statik.go
  pkg/operator/internal/webhooks/kubecarrier_webhook.go
  pkg/operator/internal/webhooks/kubecarrier_webhook_test.go
  pkg/operator/operator.go
  test/testdata/kubecarrier-config.yaml
  test/testdata/statik.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#508 Added aditional users to test htpasswd secret
  test/testdata/htpassword-secret.yaml
  test/testdata/statik.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#509 Removed unnecessary logging
  pkg/apiserver/apiserver.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#512 move validate-prow-yaml job to infra repo
  .prow.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#511 increased APIServer limits
  config/internal/apiserver/manager/manager.yaml
  pkg/internal/resources/apiserver/apiserver.golden.yaml
  pkg/internal/resources/apiserver/statik.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#513 Added boilerplate to dev image
  Makefile
  config/dockerfiles/dev.Dockerfile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#515 Added missing age field to printer columns
  config/internal/manager/crd/bases/kubecarrier.io_customresourcediscoveries.yaml
  pkg/apis/core/v1alpha1/customresourcediscovery_types.go
  pkg/internal/resources/manager/manager.golden.yaml
  pkg/internal/resources/manager/statik.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#514 Fix customResourceDiscoverySet controller
  pkg/manager/internal/controllers/catalogentryset_controller.go
  pkg/manager/internal/controllers/customresourcediscoveryset_controller.go
  pkg/manager/internal/controllers/customresourcediscoveryset_controller_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#518 Update prow configuration to use the v6 dev image
  .prow.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#500 use kubermatic-labs/boilerplate
  hack/boilerplate/boilerplate.go
  hack/boilerplate/boilerplate_test.go
  hack/boilerplate/test/fail.go
  hack/boilerplate/test/fail.py
  hack/boilerplate/test/pass.go
  hack/boilerplate/test/pass.py
  hack/verify-boilerplate.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#519 Replace sudo chown with --user flag in docker
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#520 Enable verbose for boilerplate
  hack/verify-boilerplate.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#516 Expose log level in KubeCarrier CRD
  config/internal/catapult/manager/manager.yaml
  config/internal/elevator/manager/manager.yaml
  config/internal/ferry/manager/manager.yaml
  config/internal/manager/manager/manager.yaml
  config/operator/crd/bases/operator.kubecarrier.io_apiservers.yaml
  config/operator/crd/bases/operator.kubecarrier.io_catapults.yaml
  config/operator/crd/bases/operator.kubecarrier.io_elevators.yaml
  config/operator/crd/bases/operator.kubecarrier.io_ferries.yaml
  config/operator/crd/bases/operator.kubecarrier.io_kubecarriers.yaml
  config/operator/manager/manager.yaml
  config/operator/webhook/manifests.yaml
  go.mod
  go.sum
  pkg/apis/operator/v1alpha1/apiserver_types.go
  pkg/apis/operator/v1alpha1/catapult_types.go
  pkg/apis/operator/v1alpha1/elevator_types.go
  pkg/apis/operator/v1alpha1/ferry_types.go
  pkg/apis/operator/v1alpha1/kubecarrier_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/cli/internal/cmd/setup/setup.go
  pkg/internal/resources/apiserver/apiserver.go
  pkg/internal/resources/apiserver/apiserver.golden.yaml
  pkg/internal/resources/catapult/catapult.go
  pkg/internal/resources/catapult/catapult.golden.yaml
  pkg/internal/resources/catapult/statik.go
  pkg/internal/resources/elevator/elevator.go
  pkg/internal/resources/elevator/elevator.golden.yaml
  pkg/internal/resources/elevator/statik.go
  pkg/internal/resources/ferry/ferry.go
  pkg/internal/resources/ferry/ferry.golden.yaml
  pkg/internal/resources/ferry/statik.go
  pkg/internal/resources/manager/manager.go
  pkg/internal/resources/manager/manager.golden.yaml
  pkg/internal/resources/manager/statik.go
  pkg/internal/resources/operator/operator.go
  pkg/internal/resources/operator/operator.golden.yaml
  pkg/internal/resources/operator/statik.go
  pkg/internal/util/webhook/webhook.go
  pkg/manager/internal/controllers/customresourcediscovery_controller.go
  pkg/manager/internal/controllers/derivedcustomresource_controller.go
  pkg/manager/internal/controllers/servicecluster_controller.go
  pkg/operator/internal/controllers/catapult_controller.go
  pkg/operator/internal/controllers/elevator_controller.go
  pkg/operator/internal/controllers/ferry_controller.go
  pkg/operator/internal/controllers/kubecarrier_controller.go
  pkg/operator/internal/webhooks/apiserver_webhook.go
  pkg/operator/internal/webhooks/catapult_webhook.go
  pkg/operator/internal/webhooks/elevator_webhook.go
  pkg/operator/internal/webhooks/ferry_webhook.go
  pkg/operator/operator.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#521 Use NewKindWithCache
  pkg/catapult/internal/controllers/adoption_controller.go
  pkg/catapult/internal/controllers/managementclusterobj_controller.go
  pkg/ferry/internal/controllers/customresourcediscovery_controller.go
  pkg/ferry/internal/controllers/serviceclusterassignment_controller.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#525 Add common labels to service selector, to avoid service endpoint overlap
  pkg/internal/resources/apiserver/apiserver.go
  pkg/internal/resources/catapult/catapult.go
  pkg/internal/resources/catapult/catapult.golden.yaml
  pkg/internal/resources/constants/labels.go
  pkg/internal/resources/elevator/elevator.go
  pkg/internal/resources/elevator/elevator.golden.yaml
  pkg/internal/resources/ferry/ferry.go
  pkg/internal/resources/manager/manager.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#529 rename service catalog to service hub
  README.md
  docs/api_reference/_index.md
  hack/docgen.sh
  hack/krew-manifest/main.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#532 Enable make docs in make generate
  Makefile
  docs/api_reference/_index.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#531 Deprecate KindOverride fields and use internal api group.
  config/internal/manager/crd/bases/catalog.kubecarrier.io_catalogentries.yaml
  config/internal/manager/crd/bases/catalog.kubecarrier.io_catalogentrysets.yaml
  config/internal/manager/crd/bases/catalog.kubecarrier.io_derivedcustomresources.yaml
  config/internal/manager/crd/bases/kubecarrier.io_customresourcediscoveries.yaml
  config/internal/manager/crd/bases/kubecarrier.io_customresourcediscoverysets.yaml
  docs/api_reference/_index.md
  docs/manifests/catalogentryset.yaml
  pkg/apis/catalog/v1alpha1/catalogentry_types.go
  pkg/apis/catalog/v1alpha1/catalogentryset_types.go
  pkg/apis/catalog/v1alpha1/derivedcustomresource_types.go
  pkg/apis/core/v1alpha1/customresourcediscovery_types.go
  pkg/apis/core/v1alpha1/customresourcediscoveryset_types.go
  pkg/internal/constants/kubecarrier.go
  pkg/internal/resources/manager/manager.golden.yaml
  pkg/internal/resources/manager/statik.go
  pkg/manager/internal/controllers/catalogentry_controller.go
  pkg/manager/internal/controllers/catalogentry_controller_test.go
  pkg/manager/internal/controllers/catalogentryset_controller.go
  pkg/manager/internal/controllers/catalogentryset_controller_test.go
  pkg/manager/internal/controllers/customresourcediscovery_controller.go
  pkg/manager/internal/controllers/customresourcediscovery_controller_test.go
  pkg/manager/internal/controllers/customresourcediscoveryset_controller.go
  pkg/manager/internal/controllers/customresourcediscoveryset_controller_test.go
  pkg/manager/internal/controllers/derivedcustomresource_controller.go
  pkg/manager/internal/controllers/derivedcustomresource_controller_test.go
  pkg/manager/internal/webhooks/customresourcediscovery_webhook.go
  pkg/manager/internal/webhooks/customresourcediscovery_webhook_test.go
  test/integration/apiserver.go
  test/integration/derivedcr.go
  test/integration/servicecluster.go
  test/scenarios/simple.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L
