Repository kubermatic/kubecarrier, pull requests merged in 2020-11, with the labels that each got.

#379 [WIP] Diagrams
  docs/getting_started/50_catalogs.md
  docs/getting_started/60_crds.md
  docs/img/catapult.png
  docs/img/catapult.svg
  docs/img/crds.png
  docs/img/crds.svg
Labels: approved, dco-signoff: yes, do-not-merge/work-in-progress, priority/icebox, release-note-none, size/S

#551 Create get-kubeconfig.sh
  hack/get-servicecluster-kubeconfig.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#554 Add KubeCarrier addon for KKP
  config/addon/README.md
  config/addon/cert-manager-config.yaml
  config/addon/cert-manager/cert-manager.yaml
  config/addon/kubecarrier-config.yaml
  config/addon/kubecarrier/kubecarrier.yaml
  config/addon/kubecarrier/operator.yaml
  config/addon/kubecarrier/service-cluster.yaml
  config/addon/kustomization.yaml
  config/addon/loglevel_patch.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL
