Repository kubermatic/kubecarrier, pull requests merged in 2020-05, with the labels that each got.

#407 Dev image
  .prow.yaml
  Makefile
  config/dockerfiles/dev.Dockerfile
  hack/proto-codegen.sh
  hack/validate-directory-clean.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#409 Change KubeCarrier api package from kubecarrier.api.v1alpha1 to kubecarrier.api.v1
  pkg/apiserver/api/v1/kubecarrier.pb.go
  pkg/apiserver/api/v1/kubecarrier.proto
  pkg/apiserver/api/v1/kubecarrier.swagger.json
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#410 Code generators selinux
  .prow.yaml
  Makefile
  config/dockerfiles/dev.Dockerfile
  go.mod
  go.sum
  pkg/internal/kustomize/kustomize.go
  pkg/internal/resources/apiserver/statik.go
  pkg/internal/resources/apiserver/z_init.go
  pkg/internal/resources/catapult/statik.go
  pkg/internal/resources/catapult/z_init.go
  pkg/internal/resources/elevator/statik.go
  pkg/internal/resources/elevator/z_init.go
  pkg/internal/resources/fakeoperator/statik.go
  pkg/internal/resources/fakeoperator/z_init.go
  pkg/internal/resources/ferry/statik.go
  pkg/internal/resources/ferry/z_init.go
  pkg/internal/resources/manager/statik.go
  pkg/internal/resources/manager/z_init.go
  pkg/internal/resources/operator/statik.go
  pkg/internal/resources/operator/z_init.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#413 Add boilerplate file for *.proto files
  hack/boilerplate/boilerplate.proto.txt
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#416 Enforce TLS for API Server
  pkg/apiserver/apiserver.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#412 [API Server] Offering service
  config/internal/apiserver/rbac/role.yaml
  pkg/apiserver/api/v1/meta.pb.go
  pkg/apiserver/api/v1/meta.proto
  pkg/apiserver/api/v1/meta.swagger.json
  pkg/apiserver/api/v1/offering.pb.go
  pkg/apiserver/api/v1/offering.pb.gw.go
  pkg/apiserver/api/v1/offering.proto
  pkg/apiserver/api/v1/offering.swagger.json
  pkg/apiserver/api/v1/types.pb.go
  pkg/apiserver/api/v1/types.proto
  pkg/apiserver/api/v1/types.swagger.json
  pkg/apiserver/apiserver.go
  pkg/apiserver/internal/util/util.go
  pkg/apiserver/internal/v1/apiserver_test.go
  pkg/apiserver/internal/v1/offering.go
  pkg/apiserver/internal/v1/offering_test.go
  pkg/internal/resources/apiserver/apiserver.golden.yaml
  pkg/internal/resources/apiserver/statik.go
  test/integration/apiserver.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#422 Fix two typos in offering service
  pkg/apiserver/internal/v1/offering.go
Labels: approved, dco-signoff: yes, release-note-none, size/XS

#402 [API Server] Region service
  config/internal/apiserver/rbac/role.yaml
  pkg/apiserver/api/v1/region.pb.go
  pkg/apiserver/api/v1/region.pb.gw.go
  pkg/apiserver/api/v1/region.proto
  pkg/apiserver/api/v1/region.swagger.json
  pkg/apiserver/apiserver.go
  pkg/apiserver/internal/v1/region.go
  pkg/apiserver/internal/v1/region_test.go
  pkg/internal/resources/apiserver/apiserver.golden.yaml
  pkg/internal/resources/apiserver/statik.go
  test/integration/apiserver.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#423 Update dev image
  .prow.yaml
  Makefile
  config/dockerfiles/dev.Dockerfile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#411 [API Server] Provider service
  config/internal/apiserver/rbac/role.yaml
  pkg/apiserver/api/v1/provider.pb.go
  pkg/apiserver/api/v1/provider.pb.gw.go
  pkg/apiserver/api/v1/provider.proto
  pkg/apiserver/api/v1/provider.swagger.json
  pkg/apiserver/apiserver.go
  pkg/apiserver/internal/v1/provider.go
  pkg/apiserver/internal/v1/provider_test.go
  pkg/internal/resources/apiserver/apiserver.golden.yaml
  pkg/internal/resources/apiserver/statik.go
  test/integration/apiserver.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#428 fix e2e operator default config params
  pkg/apis/fake/v1/db_types.go
  pkg/fakeoperator/internal/webhooks/db_webhook_test.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#433 kind 0.8.x workaround
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#432 Disable debugging log of CLI
  pkg/internal/reconcile/admissionregistration.go
  pkg/internal/reconcile/certmanager.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#434 Bring docs up-to-date with docs.loodse.com
  Makefile
  docs/_index.md
  docs/api_reference/_index.md
  docs/architecture/_index.md
  docs/getting_started/10_requirements.md
  docs/getting_started/20_installation.md
  docs/getting_started/30_accounts.md
  docs/getting_started/40_clusters.md
  docs/getting_started/50_catalogs.md
  docs/getting_started/60_crds.md
  docs/getting_started/_index.md
  docs/glossary/_index.md
  docs/repository_organization/_index.md
  hack/docgen.sh
  hack/validate-directory-clean.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#436 add account missing metadata
  docs/manifests/accounts.yaml
  pkg/manager/internal/webhooks/account_webhook.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#418 API server OIDC integration
  Makefile
  config/internal/apiserver/manager/manager.yaml
  config/operator/crd/bases/operator.kubecarrier.io_apiservers.yaml
  docs/api_reference/_index.md
  go.mod
  go.sum
  hack/gen-tasks.go
  pkg/apis/operator/v1alpha1/apiserver_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/apiserver/api/v1/kubecarrier.pb.go
  pkg/apiserver/api/v1/kubecarrier.pb.gw.go
  pkg/apiserver/api/v1/kubecarrier.proto
  pkg/apiserver/api/v1/kubecarrier.swagger.json
  pkg/apiserver/apiserver.go
  pkg/apiserver/internal/oidc/oidc.go
  pkg/apiserver/internal/oidc/oidc_unsafe.go
  pkg/apiserver/internal/v1/kubecarrier.go
  pkg/cli/internal/cmd/e2e-test/main.go
  pkg/cli/internal/cmd/sut/sut.go
  pkg/internal/resources/apiserver/apiserver.go
  pkg/internal/resources/apiserver/apiserver.golden.yaml
  pkg/internal/resources/apiserver/statik.go
  pkg/internal/resources/operator/operator.golden.yaml
  pkg/internal/resources/operator/statik.go
  pkg/testutil/dex.go
  test/integration/apiserver.go
  test/integration/integration.go
  test/testdata/00_prereq.yaml
  test/testdata/dex_values.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#439 Disable debug log for CLI
  pkg/internal/util/cmd.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#435 Clean up README.md
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL
