Repository kubermatic/kubecarrier, pull requests merged in 2020-03, with the labels that each got.

#283 Fixed krew manifest URL for windows
  hack/krew-manifest/main.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#244 Implementing new testing strategy and refactoring
  Makefile
  config/serviceCluster/e2e-role.yaml
  hack/gen-tasks.go
  pkg/cli/internal/cmd/e2e-test/main.go
  pkg/cli/internal/cmd/e2e-test/run.go
  pkg/cli/internal/cmd/setup/setup.go
  pkg/internal/util/clientwatcher.go
  pkg/internal/util/object.go
  pkg/testutil/framework.go
  pkg/testutil/helpers.go
  pkg/testutil/logger.go
  test/framework/framework.go
  test/installation/installation.go
  test/integration/account.go
  test/integration/catalog.go
  test/integration/derivedcr.go
  test/integration/integration.go
  test/integration/servicecluster.go
  test/provider/provider.go
  test/scenarios/scenarios.go
  test/scenarios/simple.go
  test/tenant/tenant.go
  test/test.go
  test/verify/verify.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#285 Fixed make generate
  docs/api_reference.md
  hack/docgen.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#288 Incresed catalogentrySet timeout in Scenarios/simple e2e test
  test/scenarios/simple.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#287 Dynamically set the TLS certificate secret name for name for catapult webhook
  config/internal/catapult/certmanager/certificate.yaml
  config/internal/catapult/certmanager/kustomizeconfig.yaml
  config/internal/catapult/default/kustomization.yaml
  config/internal/catapult/default/kustomizeconfig.yaml
  config/internal/catapult/default/manager_webhook_patch.yaml
  pkg/internal/resources/catapult/catapult.golden.yaml
  pkg/internal/resources/catapult/statik.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#289 [Bug-Fix]Pass the WebhookStrategy from CatalogEntrySet to CustomResourceDiscoverySet
  pkg/manager/internal/controllers/catalogentryset_controller.go
  pkg/manager/internal/controllers/catalogentryset_controller_test.go
  test/integration/servicecluster.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#250 Refaсtor operator controllers
  pkg/apis/operator/v1alpha1/catapult_types.go
  pkg/apis/operator/v1alpha1/elevator_types.go
  pkg/apis/operator/v1alpha1/ferry_types.go
  pkg/apis/operator/v1alpha1/kubecarrier_types.go
  pkg/operator/internal/controllers/base_controller.go
  pkg/operator/internal/controllers/catapult.go
  pkg/operator/internal/controllers/catapult_controller.go
  pkg/operator/internal/controllers/elevator.go
  pkg/operator/internal/controllers/elevator_controller.go
  pkg/operator/internal/controllers/ferry.go
  pkg/operator/internal/controllers/ferry_controller.go
  pkg/operator/internal/controllers/kubecarrier.go
  pkg/operator/internal/controllers/kubecarrier_controller.go
  pkg/operator/internal/controllers/util.go
  pkg/operator/operator.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#275 Webhook cleanup
  config/internal/manager/crd/bases/catalog.kubecarrier.io_accounts.yaml
  config/internal/manager/crd/bases/catalog.kubecarrier.io_catalogentries.yaml
  config/internal/manager/crd/bases/catalog.kubecarrier.io_catalogentrysets.yaml
  config/internal/manager/crd/bases/catalog.kubecarrier.io_catalogs.yaml
  config/internal/manager/crd/bases/catalog.kubecarrier.io_derivedcustomresources.yaml
  config/internal/manager/crd/bases/catalog.kubecarrier.io_offerings.yaml
  config/internal/manager/crd/bases/catalog.kubecarrier.io_providers.yaml
  config/internal/manager/crd/bases/catalog.kubecarrier.io_serviceclusterreferences.yaml
  config/internal/manager/crd/bases/kubecarrier.io_customresourcediscoveries.yaml
  config/internal/manager/crd/bases/kubecarrier.io_customresourcediscoverysets.yaml
  config/internal/manager/crd/bases/kubecarrier.io_serviceclusterassignments.yaml
  config/internal/manager/crd/bases/kubecarrier.io_serviceclusters.yaml
  config/internal/manager/webhook/manifests.yaml
  docs/api_reference.md
  pkg/apis/catalog/v1alpha1/account_types.go
  pkg/apis/catalog/v1alpha1/catalogentry_types.go
  pkg/apis/catalog/v1alpha1/catalogentryset_types.go
  pkg/apis/catalog/v1alpha1/derivedcustomresource_types.go
  pkg/apis/catalog/v1alpha1/offering_types.go
  pkg/apis/catalog/v1alpha1/provider_types.go
  pkg/apis/catalog/v1alpha1/types.go
  pkg/apis/catalog/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/v1alpha1/customresourcediscovery_types.go
  pkg/apis/core/v1alpha1/index.go
  pkg/apis/core/v1alpha1/serviceclusterassignment_types.go
  pkg/apis/core/v1alpha1/types.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/catapult/internal/controllers/adoption_controller_test.go
  pkg/catapult/internal/controllers/managementclusterobj_controller.go
  pkg/catapult/internal/controllers/managementclusterobj_controller_test.go
  pkg/ferry/internal/controllers/serviceclusterassignment_controller.go
  pkg/internal/resources/manager/manager.golden.yaml
  pkg/internal/resources/manager/statik.go
  pkg/manager/internal/controllers/account_controller.go
  pkg/manager/internal/controllers/catalog_controller_test.go
  pkg/manager/internal/controllers/catalogentry_controller_test.go
  pkg/manager/internal/controllers/customresourcediscovery_controller.go
  pkg/manager/internal/controllers/customresourcediscovery_controller_test.go
  pkg/manager/internal/controllers/customresourcediscoveryset_controller.go
  pkg/manager/internal/controllers/customresourcediscoveryset_controller_test.go
  pkg/manager/internal/controllers/derivedcustomresource_controller_test.go
  pkg/manager/internal/webhooks/account_webhook_test.go
  pkg/manager/internal/webhooks/catalogentry_webhook.go
  pkg/manager/internal/webhooks/catalogentry_webhook_test.go
  pkg/manager/internal/webhooks/customresourcediscovery_webhook.go
  pkg/manager/internal/webhooks/customresourcediscovery_webhook_test.go
  pkg/manager/internal/webhooks/derivedcustomresource_webhook.go
  pkg/manager/internal/webhooks/derivedcustomresource_webhook_test.go
  pkg/manager/internal/webhooks/offering_webhook.go
  pkg/manager/internal/webhooks/offering_webhook_test.go
  pkg/manager/internal/webhooks/provider_webhook.go
  pkg/manager/internal/webhooks/serviceclusterassignment_webhook.go
  pkg/manager/internal/webhooks/serviceclusterassignment_webhook_test.go
  pkg/manager/internal/webhooks/serviceclusterreference_webhook.go
  pkg/manager/internal/webhooks/serviceclusterreference_webhook_test.go
  test/integration/catalog.go
  test/integration/derivedcr.go
  test/integration/servicecluster.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#276 Dynamic Elevator Webhook
  config/internal/elevator/certmanager/certificate.yaml
  config/internal/elevator/certmanager/kustomizeconfig.yaml
  config/internal/elevator/default/kustomization.yaml
  config/internal/elevator/default/kustomizeconfig.yaml
  config/internal/elevator/default/manager_webhook_patch.yaml
  config/internal/elevator/default/webhookcainjection_patch.yaml
  config/internal/elevator/manager/manager.yaml
  pkg/elevator/elevator.go
  pkg/elevator/internal/controllers/adoption_controller.go
  pkg/elevator/internal/controllers/tenantobj_controller.go
  pkg/elevator/internal/util/util.go
  pkg/elevator/internal/util/util_test.go
  pkg/elevator/internal/webhooks/tenantobj_webhook.go
  pkg/internal/resources/catapult/catapult.go
  pkg/internal/resources/catapult/catapult.golden.yaml
  pkg/internal/resources/elevator/elevator.go
  pkg/internal/resources/elevator/elevator.golden.yaml
  pkg/internal/resources/elevator/statik.go
  pkg/operator/internal/controllers/elevator.go
  test/integration/derivedcr.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#304 propagate deletion error upwards
  pkg/internal/util/object.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#292 Add a test to check if the catapult webhook service is deployed
  pkg/catapult/internal/webhooks/managementclusterobj_webhook.go
  test/integration/servicecluster.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#306 Add liveness probe for manager
  config/internal/manager/manager/manager.yaml
  pkg/internal/resources/manager/manager.golden.yaml
  pkg/internal/resources/manager/statik.go
  pkg/manager/manager.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#307 Dynamically set the TLS certificate secret name for manager webhook service
  config/internal/manager/certmanager/certificate.yaml
  config/internal/manager/certmanager/kustomizeconfig.yaml
  config/internal/manager/default/kustomization.yaml
  config/internal/manager/default/kustomizeconfig.yaml
  config/internal/manager/default/manager_webhook_patch.yaml
  pkg/internal/resources/manager/manager.golden.yaml
  pkg/internal/resources/manager/statik.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#305 Added account deletion helper
  hack/gen-tasks.go
  pkg/cli/internal/cmd/delete/account.go
  pkg/cli/internal/cmd/delete/delete.go
  pkg/cli/internal/cmd/root.go
  pkg/testutil/framework.go
  test/integration/cli.go
  test/integration/integration.go
  test/integration/servicecluster.go
  test/scenarios/simple.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#310 Upgrade controller-gen to v0.2.8
  config/internal/manager/crd/bases/catalog.kubecarrier.io_accounts.yaml
  config/internal/manager/crd/bases/catalog.kubecarrier.io_catalogentries.yaml
  config/internal/manager/crd/bases/catalog.kubecarrier.io_catalogentrysets.yaml
  config/internal/manager/crd/bases/catalog.kubecarrier.io_catalogs.yaml
  config/internal/manager/crd/bases/catalog.kubecarrier.io_derivedcustomresources.yaml
  config/internal/manager/crd/bases/catalog.kubecarrier.io_offerings.yaml
  config/internal/manager/crd/bases/catalog.kubecarrier.io_providers.yaml
  config/internal/manager/crd/bases/catalog.kubecarrier.io_serviceclusterreferences.yaml
  config/internal/manager/crd/bases/catalog.kubecarrier.io_tenants.yaml
  config/internal/manager/crd/bases/kubecarrier.io_customresourcediscoveries.yaml
  config/internal/manager/crd/bases/kubecarrier.io_customresourcediscoverysets.yaml
  config/internal/manager/crd/bases/kubecarrier.io_serviceclusterassignments.yaml
  config/internal/manager/crd/bases/kubecarrier.io_serviceclusters.yaml
  config/operator/crd/bases/operator.kubecarrier.io_catapults.yaml
  config/operator/crd/bases/operator.kubecarrier.io_elevators.yaml
  config/operator/crd/bases/operator.kubecarrier.io_ferries.yaml
  config/operator/crd/bases/operator.kubecarrier.io_kubecarriers.yaml
  hack/codegen.sh
  pkg/internal/resources/manager/manager.golden.yaml
  pkg/internal/resources/manager/statik.go
  pkg/internal/resources/operator/operator.golden.yaml
  pkg/internal/resources/operator/statik.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#309 DerivedCR deletion webhook
  config/internal/manager/crd/bases/catalog.kubecarrier.io_derivedcustomresources.yaml
  config/internal/manager/rbac/agg_role.yaml
  config/internal/manager/rbac/agg_role_binding.yaml
  config/internal/manager/rbac/kustomization.yaml
  config/internal/manager/rbac/role.yaml
  config/internal/manager/webhook/manifests.yaml
  docs/api_reference.md
  go.sum
  hack/codegen.sh
  pkg/apis/catalog/v1alpha1/derivedcustomresource_types.go
  pkg/apis/catalog/v1alpha1/zz_generated.deepcopy.go
  pkg/internal/resources/catapult/statik.go
  pkg/internal/resources/elevator/elevator.go
  pkg/internal/resources/elevator/elevator.golden.yaml
  pkg/internal/resources/elevator/statik.go
  pkg/internal/resources/ferry/statik.go
  pkg/internal/resources/manager/manager.golden.yaml
  pkg/internal/resources/manager/statik.go
  pkg/internal/resources/operator/statik.go
  pkg/manager/internal/controllers/catalogentry_controller_test.go
  pkg/manager/internal/controllers/derivedcustomresource_controller.go
  pkg/manager/internal/webhooks/derivedcustomresource_webhook.go
  pkg/manager/manager.go
  test/integration/derivedcr.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#311 Set kubernetes recommanded labels for operator-managed objects
  pkg/internal/resources/catapult/catapult.go
  pkg/internal/resources/catapult/catapult.golden.yaml
  pkg/internal/resources/constants/labels.go
  pkg/internal/resources/elevator/elevator.go
  pkg/internal/resources/elevator/elevator.golden.yaml
  pkg/internal/resources/ferry/ferry.go
  pkg/internal/resources/ferry/ferry.golden.yaml
  pkg/internal/resources/manager/manager.go
  pkg/internal/resources/manager/manager.golden.yaml
  pkg/internal/resources/manager/manager_test.go
  pkg/internal/resources/manager/statik.go
  pkg/operator/internal/controllers/kubecarrier.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#314 Remove the default assignee in the feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#317 Upgrade the cert-manager to v0.14.0
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#315 CustomResourceDiscovery deletion webhook
  config/internal/manager/webhook/manifests.yaml
  pkg/internal/resources/catapult/catapult.go
  pkg/internal/resources/catapult/catapult.golden.yaml
  pkg/internal/resources/manager/manager.golden.yaml
  pkg/internal/resources/manager/statik.go
  pkg/manager/internal/controllers/customresourcediscovery_controller.go
  pkg/manager/internal/webhooks/customresourcediscovery_webhook.go
  pkg/manager/manager.go
  test/integration/servicecluster.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#320 Improved e2e test
  hack/.e2e-test.sh
  test/integration/account.go
  test/integration/catalog.go
  test/integration/servicecluster.go
  test/scenarios/simple.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#319 Add make generate to CI/CD
  Makefile
  config/dockerfiles/test.Dockerfile
  hack/validate-directory-clean.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#321 Upgrade golangci-lint to v1.24.0
  config/dockerfiles/test.Dockerfile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#318 Fix lints
  hack/docgen/main.go
  pkg/manager/internal/controllers/catalogentry_controller.go
  pkg/manager/internal/webhooks/provider_webhook.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#284 Updated krew manifest information
  hack/krew-manifest/main.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#334 disabling CustromResourceDiscovery/DerivedCustromResource deletion webhooks
  pkg/manager/internal/webhooks/customresourcediscovery_webhook.go
  pkg/manager/internal/webhooks/derivedcustomresource_webhook.go
  test/integration/derivedcr.go
  test/integration/servicecluster.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#333 Bootstrap tower
  Makefile
  cmd/tower/main.go
  config/dockerfiles/tower.Dockerfile
  hack/gen-tasks.go
  pkg/tower/tower.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#336 Fix conflicting cluster role names for same named catapult & elevator
  pkg/internal/resources/catapult/catapult.go
  pkg/internal/resources/catapult/catapult.golden.yaml
  pkg/internal/resources/elevator/elevator.go
  pkg/internal/resources/elevator/elevator.golden.yaml
  pkg/manager/internal/webhooks/customresourcediscovery_webhook.go
  pkg/manager/internal/webhooks/derivedcustomresource_webhook.go
  test/integration/servicecluster.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#335 Add Tower to Operator
  config/internal/tower/certmanager/certificate.yaml
  config/internal/tower/certmanager/kustomization.yaml
  config/internal/tower/certmanager/kustomizeconfig.yaml
  config/internal/tower/default/kustomization.yaml
  config/internal/tower/default/manager_webhook_patch.yaml
  config/internal/tower/default/webhookcainjection_patch.yaml
  config/internal/tower/manager/kustomization.yaml
  config/internal/tower/manager/manager.yaml
  config/internal/tower/prometheus/kustomization.yaml
  config/internal/tower/prometheus/monitor.yaml
  config/internal/tower/rbac/kustomization.yaml
  config/internal/tower/rbac/leader_election_role.yaml
  config/internal/tower/rbac/leader_election_role_binding.yaml
  config/internal/tower/rbac/role.yaml
  config/internal/tower/rbac/role_binding.yaml
  config/internal/tower/webhook/kustomization.yaml
  config/internal/tower/webhook/kustomizeconfig.yaml
  config/internal/tower/webhook/manifests.yaml
  config/internal/tower/webhook/service.yaml
  config/operator/crd/bases/operator.kubecarrier.io_towers.yaml
  config/operator/crd/kustomization.yaml
  config/operator/rbac/role.yaml
  docs/api_reference.md
  hack/codegen.sh
  pkg/apis/operator/v1alpha1/tower_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/internal/resources/operator/operator.golden.yaml
  pkg/internal/resources/operator/statik.go
  pkg/internal/resources/tower/statik.go
  pkg/internal/resources/tower/tower.go
  pkg/internal/resources/tower/tower.golden.yaml
  pkg/internal/resources/tower/tower_test.go
  pkg/internal/resources/tower/z_init.go
  pkg/operator/internal/controllers/tower.go
  pkg/operator/operator.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#313 CLI: implement the preflight checks
  pkg/cli/internal/cmd/preflight/checkers/checkers.go
  pkg/cli/internal/cmd/preflight/checkers/checkers_test.go
  pkg/cli/internal/cmd/preflight/checkers/crd.go
  pkg/cli/internal/cmd/preflight/checkers/crd_test.go
  pkg/cli/internal/cmd/preflight/checkers/kubernetes.go
  pkg/cli/internal/cmd/preflight/checkers/kubernetes_test.go
  pkg/cli/internal/cmd/preflight/preflight.go
  pkg/cli/internal/cmd/root.go
  pkg/cli/internal/cmd/setup/setup.go
  pkg/internal/util/ready.go
  pkg/manager/internal/controllers/customresourcediscovery_controller.go
  pkg/manager/internal/controllers/derivedcustomresource_controller.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#348 Enable deletion webhook test for DerivedCustomResource
  test/integration/derivedcr.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#351 [README.md update] Update cert-manger to v0.14.0
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#337 Service cluster monitor grace period
  pkg/manager/internal/controllers/servicecluster_controller.go
  pkg/manager/internal/controllers/servicecluster_controller_test.go
  pkg/manager/manager.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#332 Rename ServiceClusterReference to Region
  README.md
  config/internal/manager/crd/bases/catalog.kubecarrier.io_catalogentries.yaml
  config/internal/manager/crd/bases/catalog.kubecarrier.io_offerings.yaml
  config/internal/manager/crd/bases/catalog.kubecarrier.io_regions.yaml
  config/internal/manager/crd/kustomization.yaml
  config/internal/manager/crd/patches/cainjection_in_regions.yaml
  config/internal/manager/crd/patches/webhook_in_regions.yaml
  config/internal/manager/rbac/role.yaml
  config/internal/manager/webhook/manifests.yaml
  docs/api_reference.md
  pkg/apis/catalog/v1alpha1/crds_types.go
  pkg/apis/catalog/v1alpha1/region_types.go
  pkg/apis/catalog/v1alpha1/zz_generated.deepcopy.go
  pkg/internal/resources/manager/manager.golden.yaml
  pkg/internal/resources/manager/statik.go
  pkg/manager/internal/controllers/account_controller.go
  pkg/manager/internal/controllers/catalog_controller.go
  pkg/manager/internal/controllers/catalog_controller_test.go
  pkg/manager/internal/controllers/catalogentry_controller.go
  pkg/manager/internal/controllers/catalogentry_controller_test.go
  pkg/manager/internal/webhooks/serviceclusterreference_webhook.go
  pkg/manager/internal/webhooks/serviceclusterreference_webhook_test.go
  pkg/manager/manager.go
  test/integration/catalog.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#322 Adding docker images to our release
  .goreleaser.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#347 KubeCarrier default
  config/operator/certmanager/certificate.yaml
  config/operator/certmanager/kustomizeconfig.yaml
  config/operator/crd/bases/operator.kubecarrier.io_kubecarriers.yaml
  config/operator/crd/kustomization.yaml
  config/operator/default/kustomization.yaml
  config/operator/default/kustomizeconfig.yaml
  config/operator/default/manager_webhook_patch.yaml
  config/operator/default/webhookcainjection_patch.yaml
  config/operator/manager/manager.yaml
  config/operator/webhook/manifests.yaml
  hack/codegen.sh
  pkg/apis/operator/v1alpha1/kubecarrier_types.go
  pkg/cli/internal/cmd/setup/setup.go
  pkg/internal/constants/kubecarrier.go
  pkg/internal/resources/operator/operator.golden.yaml
  pkg/internal/resources/operator/statik.go
  pkg/operator/internal/controllers/base_controller.go
  pkg/operator/internal/controllers/kubecarrier.go
  pkg/operator/internal/webhooks/kubecarrier_webhook.go
  pkg/operator/internal/webhooks/kubecarrier_webhook_test.go
  pkg/operator/operator.go
  test/installation/installation.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL
