Repository kubermatic/kubecarrier, pull requests merged in 2020-06, with the labels that each got.

#426 [API Server] Use general ListRequest and GetRequest in services
  pkg/apiserver/api/v1/offering.pb.go
  pkg/apiserver/api/v1/offering.pb.gw.go
  pkg/apiserver/api/v1/offering.proto
  pkg/apiserver/api/v1/provider.pb.go
  pkg/apiserver/api/v1/provider.pb.gw.go
  pkg/apiserver/api/v1/provider.proto
  pkg/apiserver/api/v1/region.pb.go
  pkg/apiserver/api/v1/region.pb.gw.go
  pkg/apiserver/api/v1/region.proto
  pkg/apiserver/api/v1/request.pb.go
  pkg/apiserver/api/v1/request.proto
  pkg/apiserver/api/v1/request.swagger.json
  pkg/apiserver/internal/v1/offering.go
  pkg/apiserver/internal/v1/offering_test.go
  pkg/apiserver/internal/v1/provider.go
  pkg/apiserver/internal/v1/provider_test.go
  pkg/apiserver/internal/v1/region.go
  pkg/apiserver/internal/v1/region_test.go
  pkg/apiserver/internal/v1/util.go
  pkg/apiserver/internal/v1/validation.go
  pkg/apiserver/internal/v1/validation_test.go
  test/integration/apiserver.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#424 Add services API
  config/internal/apiserver/rbac/agg_role.yaml
  config/internal/apiserver/rbac/agg_role_binding.yaml
  config/internal/apiserver/rbac/kustomization.yaml
  pkg/apiserver/api/v1/instance.pb.go
  pkg/apiserver/api/v1/instance.pb.gw.go
  pkg/apiserver/api/v1/instance.proto
  pkg/apiserver/api/v1/instance.swagger.json
  pkg/apiserver/api/v1/util.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/internal/v1/instance.go
  pkg/apiserver/internal/v1/instance_test.go
  pkg/apiserver/internal/v1/util.go
  pkg/internal/resources/apiserver/apiserver.golden.yaml
  pkg/internal/resources/apiserver/statik.go
  pkg/internal/resources/elevator/elevator.go
  pkg/internal/resources/elevator/elevator.golden.yaml
  pkg/testutil/framework.go
  pkg/testutil/helpers.go
  test/integration/account.go
  test/integration/apiserver.go
  test/integration/catalog.go
  test/integration/cli.go
  test/integration/derivedcr.go
  test/integration/fakedb.go
  test/integration/servicecluster.go
  test/scenarios/simple.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#437 [API Server] Account Service
  config/internal/apiserver/rbac/role.yaml
  pkg/apiserver/api/v1/account.pb.go
  pkg/apiserver/api/v1/account.pb.gw.go
  pkg/apiserver/api/v1/account.proto
  pkg/apiserver/api/v1/account.swagger.json
  pkg/apiserver/api/v1/types.pb.go
  pkg/apiserver/api/v1/types.proto
  pkg/apiserver/apiserver.go
  pkg/apiserver/internal/v1/account.go
  pkg/apiserver/internal/v1/account_test.go
  pkg/apiserver/internal/v1/util.go
  pkg/internal/resources/apiserver/apiserver.golden.yaml
  pkg/internal/resources/apiserver/statik.go
  test/integration/apiserver.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#449 add validation for instance create/delete req
  pkg/apiserver/internal/v1/instance.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#451 Fix watcher.Stop() on a nil watcher
  pkg/apiserver/internal/v1/offering.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#454 Add init-system to test container
  .prow.yaml
  config/dockerfiles/test.Dockerfile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#455 Install go-init in dev image
  .prow.yaml
  Makefile
  config/dockerfiles/dev.Dockerfile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#452 Combine swagger definitions, add API information
  hack/proto-codegen.sh
  pkg/apiserver/api/v1/account.swagger.json
  pkg/apiserver/api/v1/apidocs.swagger.json
  pkg/apiserver/api/v1/event.swagger.json
  pkg/apiserver/api/v1/instance.swagger.json
  pkg/apiserver/api/v1/kubecarrier.swagger.json
  pkg/apiserver/api/v1/meta.swagger.json
  pkg/apiserver/api/v1/offering.swagger.json
  pkg/apiserver/api/v1/provider.swagger.json
  pkg/apiserver/api/v1/region.swagger.json
  pkg/apiserver/api/v1/request.swagger.json
  pkg/apiserver/api/v1/types.swagger.json
  pkg/apiserver/api/v1/v1.pb.go
  pkg/apiserver/api/v1/v1.proto
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#459 Refactored authN handling in the API server
  go.mod
  go.sum
  pkg/apiserver/apiserver.go
  pkg/apiserver/auth/auth.go
  pkg/apiserver/internal/auth/anonymous/anonymous.go
  pkg/apiserver/internal/auth/oidc/oidc.go
  pkg/apiserver/internal/auth/oidc/oidc_unsafe.go
  pkg/apiserver/internal/v1/account.go
  pkg/apiserver/internal/v1/kubecarrier.go
  pkg/internal/util/cmd.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#464 Kind upgrade to v0.8.1
  .prow.yaml
  config/dockerfiles/test.Dockerfile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#466 kind cluster sync creation
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#463 fixed JSON REST API calls skipping gRPC middlewares
  pkg/apiserver/apiserver.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#460 KubeCarrier deploys API Server
  .prow.yaml
  config/internal/apiserver/certmanager/certificate.yaml
  config/internal/apiserver/default/kustomization.yaml
  config/operator/crd/bases/operator.kubecarrier.io_apiservers.yaml
  config/operator/crd/bases/operator.kubecarrier.io_kubecarriers.yaml
  config/operator/rbac/role.yaml
  pkg/apis/operator/v1alpha1/apiserver_types.go
  pkg/apis/operator/v1alpha1/kubecarrier_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/apiserver/apiserver.go
  pkg/cli/internal/cmd/setup/setup.go
  pkg/internal/resources/apiserver/apiserver.go
  pkg/internal/resources/apiserver/apiserver.golden.yaml
  pkg/internal/resources/apiserver/apiserver_test.go
  pkg/internal/resources/apiserver/statik.go
  pkg/internal/resources/operator/operator.golden.yaml
  pkg/internal/resources/operator/statik.go
  pkg/operator/internal/controllers/apiserver_controller.go
  pkg/operator/internal/controllers/kubecarrier_controller.go
  pkg/testutil/framework.go
  test/integration/apiserver.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#401 Authorization
  config/internal/apiserver/rbac/role.yaml
  pkg/apiserver/apiserver.go
  pkg/apiserver/internal/authorizer/authorizer.go
  pkg/apiserver/internal/v1/offering.go
  pkg/apiserver/internal/v1/offering_test.go
  pkg/apiserver/internal/v1/provider.go
  pkg/apiserver/internal/v1/provider_test.go
  pkg/apiserver/internal/v1/region.go
  pkg/apiserver/internal/v1/region_test.go
  pkg/internal/resources/apiserver/apiserver.golden.yaml
  pkg/internal/resources/apiserver/statik.go
  test/integration/apiserver.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#469 [API Server] Static User Configuration
  config/internal/apiserver/rbac/role.yaml
  config/operator/crd/bases/operator.kubecarrier.io_apiservers.yaml
  config/operator/crd/bases/operator.kubecarrier.io_kubecarriers.yaml
  go.mod
  go.sum
  pkg/apis/operator/v1alpha1/apiserver_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/internal/auth/htpasswd/htpasswd.go
  pkg/apiserver/internal/auth/htpasswd/htpasswd_test.go
  pkg/internal/resources/apiserver/apiserver.go
  pkg/internal/resources/apiserver/apiserver.golden.yaml
  pkg/internal/resources/apiserver/apiserver_test.go
  pkg/internal/resources/apiserver/statik.go
  pkg/internal/resources/operator/operator.golden.yaml
  pkg/internal/resources/operator/statik.go
  test/integration/apiserver.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#471 Added all CRDs to the 'all' category
  config/internal/fake-operator/crd/bases/fake.kubecarrier.io_backups.yaml
  config/internal/fake-operator/crd/bases/fake.kubecarrier.io_dbs.yaml
  config/internal/fake-operator/crd/bases/fake.kubecarrier.io_snapshots.yaml
  config/internal/manager/crd/bases/catalog.kubecarrier.io_accounts.yaml
  config/internal/manager/crd/bases/catalog.kubecarrier.io_catalogentries.yaml
  config/internal/manager/crd/bases/catalog.kubecarrier.io_catalogentrysets.yaml
  config/internal/manager/crd/bases/catalog.kubecarrier.io_catalogs.yaml
  config/internal/manager/crd/bases/catalog.kubecarrier.io_derivedcustomresources.yaml
  config/internal/manager/crd/bases/catalog.kubecarrier.io_offerings.yaml
  config/internal/manager/crd/bases/catalog.kubecarrier.io_providers.yaml
  config/internal/manager/crd/bases/catalog.kubecarrier.io_regions.yaml
  config/internal/manager/crd/bases/catalog.kubecarrier.io_tenants.yaml
  config/internal/manager/crd/bases/kubecarrier.io_customresourcediscoverysets.yaml
  config/internal/manager/crd/bases/kubecarrier.io_serviceclusters.yaml
  config/operator/crd/bases/operator.kubecarrier.io_apiservers.yaml
  config/operator/crd/bases/operator.kubecarrier.io_catapults.yaml
  config/operator/crd/bases/operator.kubecarrier.io_elevators.yaml
  config/operator/crd/bases/operator.kubecarrier.io_ferries.yaml
  config/operator/crd/bases/operator.kubecarrier.io_kubecarriers.yaml
  pkg/apis/catalog/v1alpha1/account_types.go
  pkg/apis/catalog/v1alpha1/catalog_types.go
  pkg/apis/catalog/v1alpha1/catalogentry_types.go
  pkg/apis/catalog/v1alpha1/catalogentryset_types.go
  pkg/apis/catalog/v1alpha1/derivedcustomresource_types.go
  pkg/apis/catalog/v1alpha1/offering_types.go
  pkg/apis/catalog/v1alpha1/provider_types.go
  pkg/apis/catalog/v1alpha1/region_types.go
  pkg/apis/catalog/v1alpha1/tenant_types.go
  pkg/apis/core/v1alpha1/customresourcediscovery_types.go
  pkg/apis/core/v1alpha1/customresourcediscoveryset_types.go
  pkg/apis/core/v1alpha1/servicecluster_types.go
  pkg/apis/core/v1alpha1/serviceclusterassignment_types.go
  pkg/apis/fake/v1/backup_type.go
  pkg/apis/fake/v1/db_types.go
  pkg/apis/fake/v1/snapshot_type.go
  pkg/apis/fake/v1alpha1/db_types.go
  pkg/apis/operator/v1alpha1/apiserver_types.go
  pkg/apis/operator/v1alpha1/catapult_types.go
  pkg/apis/operator/v1alpha1/elevator_types.go
  pkg/apis/operator/v1alpha1/ferry_types.go
  pkg/apis/operator/v1alpha1/kubecarrier_types.go
  pkg/internal/resources/fakeoperator/fakeoperator.golden.yaml
  pkg/internal/resources/fakeoperator/statik.go
  pkg/internal/resources/manager/manager.golden.yaml
  pkg/internal/resources/manager/statik.go
  pkg/internal/resources/operator/operator.golden.yaml
  pkg/internal/resources/operator/statik.go
  pkg/manager/internal/controllers/customresourcediscovery_controller.go
  pkg/manager/internal/controllers/derivedcustomresource_controller.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#477 Remove SubjectAccessReview from error message
  pkg/apiserver/internal/authorizer/authorizer.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#457 refactor validation
  go.sum
  pkg/apiserver/api/v1/util.go
  pkg/apiserver/api/v1/validation.go
  pkg/apiserver/api/v1/validation_test.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/internal/v1/account.go
  pkg/apiserver/internal/v1/instance.go
  pkg/apiserver/internal/v1/instance_test.go
  pkg/apiserver/internal/v1/offering.go
  pkg/apiserver/internal/v1/offering_test.go
  pkg/apiserver/internal/v1/provider.go
  pkg/apiserver/internal/v1/provider_test.go
  pkg/apiserver/internal/v1/region.go
  pkg/apiserver/internal/v1/region_test.go
  pkg/apiserver/internal/v1/validation.go
  test/integration/apiserver.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#478 Enabled kind audit logs in the e2e tests
  Makefile
  hack/.e2e-test.sh
  hack/audit.yaml
  hack/kind-config.yaml
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#479 Watch test refactor
  test/integration/apiserver.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#481 Operator & manager perf improvements
  Makefile
  config/internal/manager/manager/manager.yaml
  config/operator/manager/manager.yaml
  go.mod
  go.sum
  hack/.e2e-test.sh
  hack/audit.yaml
  hack/codegen.sh
  hack/testjsonformat/main.go
  pkg/cli/internal/cmd/setup/setup.go
  pkg/internal/resources/manager/manager.golden.yaml
  pkg/internal/resources/manager/statik.go
  pkg/internal/resources/operator/operator.golden.yaml
  pkg/internal/resources/operator/statik.go
  pkg/operator/internal/controllers/kubecarrier_controller.go
  pkg/operator/internal/controllers/util.go
  pkg/operator/operator.go
  pkg/testutil/framework.go
  pkg/testutil/helpers.go
  test/installation/kubecarrier.go
  test/integration/apiserver.go
  test/testdata/htpassword-secret.yaml
  test/testdata/kubecarrier-config.yaml
  test/testdata/statik.go
  test/testdata/z_init.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XL

#482 Authorization refactoring
  pkg/apiserver/api/v1/auth.go
  pkg/apiserver/api/v1/util.go
  pkg/apiserver/api/v1/validation.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/internal/authorizer/authorizer.go
  pkg/apiserver/internal/v1/account.go
  pkg/apiserver/internal/v1/instance.go
  pkg/apiserver/internal/v1/offering.go
  pkg/apiserver/internal/v1/offering_test.go
  pkg/apiserver/internal/v1/provider.go
  pkg/apiserver/internal/v1/provider_test.go
  pkg/apiserver/internal/v1/region.go
  pkg/apiserver/internal/v1/region_test.go
  test/integration/apiserver.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#488 Further product stability improvements
  hack/.e2e-test.sh
  hack/audit.yaml
  hack/testjsonformat/main.go
  pkg/apiserver/internal/auth/htpasswd/htpasswd.go
  pkg/apiserver/internal/authorizer/authorizer.go
  pkg/cli/internal/cmd/sut/service.go
  pkg/cli/internal/cmd/sut/sut.go
  pkg/internal/reconcile/rbac.go
  test/integration/apiserver.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#489 Ensure that AuthRequest implemented
  pkg/apiserver/api/v1/auth.go
  pkg/apiserver/authorizer/authorizer.go
  pkg/apiserver/internal/authorizer/authorizer.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#490 add util watch method
  pkg/apiserver/internal/v1/instance.go
  pkg/apiserver/internal/v1/offering.go
  pkg/apiserver/internal/v1/util.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#462 Implements API service accounts
  config/internal/apiserver/rbac/role.yaml
  pkg/apiserver/apiserver.go
  pkg/apiserver/internal/auth/oidc/oidc.go
  pkg/apiserver/internal/auth/token/token.go
  pkg/internal/resources/apiserver/apiserver.go
  pkg/internal/resources/apiserver/apiserver.golden.yaml
  pkg/internal/resources/apiserver/statik.go
  test/integration/apiserver.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#494 Fix crd instance cleanup
  pkg/catapult/internal/controllers/adoption_controller.go
  pkg/catapult/internal/controllers/adoption_controller_test.go
  pkg/elevator/internal/controllers/adoption_controller.go
  pkg/elevator/internal/controllers/adoption_controller_test.go
  pkg/testutil/mockclient/client.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#492 Single owner override
  .prow.yaml
  pkg/catapult/internal/controllers/adoption_controller_test.go
  pkg/catapult/internal/controllers/managementclusterobj_controller.go
  pkg/elevator/internal/controllers/adoption_controller_test.go
  pkg/ferry/internal/controllers/customresourcediscovery_controller.go
  pkg/ferry/internal/controllers/serviceclusterassignment_controller.go
  pkg/internal/owner/owner.go
  pkg/internal/owner/owner_test.go
  pkg/internal/owner/reconcile.go
  pkg/internal/owner/reconcile_test.go
  pkg/manager/internal/controllers/account_controller.go
  pkg/manager/internal/controllers/catalog_controller_test.go
  pkg/manager/internal/controllers/customresourcediscovery_controller.go
  pkg/manager/internal/controllers/customresourcediscovery_controller_test.go
  pkg/manager/internal/controllers/derivedcustomresource_controller.go
  pkg/manager/internal/controllers/derivedcustomresource_controller_test.go
  pkg/operator/internal/controllers/util.go
  test/integration/account.go
  test/integration/apiserver.go
  test/integration/catalog.go
  test/integration/derivedcr.go
  test/integration/fakedb.go
  test/integration/integration.go
  test/integration/servicecluster.go
  test/scenarios/scenarios.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#495 Fix links to work in hugo rendered documentation, add additional stat…
  docs/api_reference/_index.md
  hack/docgen/main.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#496 Fix apiserver build for go-releaser
  .goreleaser.yaml
Labels: approved, dco-signoff: yes, release-note-none, size/XS
