Repository kubermatic/kubecarrier, pull requests merged in 2020-04, with the labels that each got.

#375 Moving getting started section to dedicated folder under docs
  README.md
  docs/getting_started/_index.en.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#376 fix broken link in readme
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#378 Restructured getting started into sub pages
  Makefile
  docs/_index.md
  docs/api_reference/_index.md
  docs/architecture/_index.md
  docs/getting_started/10_requirements.md
  docs/getting_started/20_installation.md
  docs/getting_started/30_accounts.md
  docs/getting_started/40_clusters.md
  docs/getting_started/50_catalogs.md
  docs/getting_started/60_crds.md
  docs/getting_started/_index.md
  docs/glossary/_index.md
  docs/repository_organization/_index.md
  hack/docgen.sh
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#377 Froce statik not to set modification dates
  hack/codegen.sh
  pkg/internal/resources/catapult/statik.go
  pkg/internal/resources/elevator/statik.go
  pkg/internal/resources/ferry/statik.go
  pkg/internal/resources/manager/statik.go
  pkg/internal/resources/operator/statik.go
  pkg/internal/resources/tower/statik.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#331 Add E2E operator
  Makefile
  cmd/fake-operator/main.go
  config/dockerfiles/fake-operator.Dockerfile
  config/internal/fake-operator/certmanager/certificate.yaml
  config/internal/fake-operator/certmanager/kustomization.yaml
  config/internal/fake-operator/certmanager/kustomizeconfig.yaml
  config/internal/fake-operator/crd/bases/fake.kubecarrier.io_dbs.yaml
  config/internal/fake-operator/crd/kustomization.yaml
  config/internal/fake-operator/crd/kustomizeconfig.yaml
  config/internal/fake-operator/default/kustomization.yaml
  config/internal/fake-operator/manager/kustomization.yaml
  config/internal/fake-operator/manager/manager.yaml
  config/internal/fake-operator/rbac/kustomization.yaml
  config/internal/fake-operator/rbac/role.yaml
  config/internal/fake-operator/rbac/role_binding.yaml
  config/serviceCluster/e2e-role.yaml
  go.mod
  hack/codegen.sh
  pkg/apis/fake/v1alpha1/db_types.go
  pkg/apis/fake/v1alpha1/groupversion_info.go
  pkg/apis/fake/v1alpha1/types.go
  pkg/apis/fake/v1alpha1/zz_generated.deepcopy.go
  pkg/cli/internal/cmd/e2e-test/main.go
  pkg/cli/internal/cmd/e2e-test/setup-e2e-operator.go
  pkg/fakeoperator/fakeoperator.go
  pkg/fakeoperator/internal/controllers/db_controller.go
  pkg/internal/resources/fakeoperator/fakeoperator.go
  pkg/internal/resources/fakeoperator/fakeoperator.golden.yaml
  pkg/internal/resources/fakeoperator/fakeoperator_test.go
  pkg/internal/resources/fakeoperator/statik.go
  pkg/internal/resources/fakeoperator/z_init.go
  pkg/testutil/framework.go
  test/installation/installation.go
  test/integration/fakedb.go
  test/integration/integration.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#383 E2E operator webhooks
  Makefile
  config/internal/fake-operator/crd/bases/fake.kubecarrier.io_dbs.yaml
  config/internal/fake-operator/crd/kustomization.yaml
  config/internal/fake-operator/crd/patches/cainjection_in_dbs.yaml
  config/internal/fake-operator/crd/patches/webhook_in_dbs.yaml
  config/internal/fake-operator/default/kustomization.yaml
  config/internal/fake-operator/default/kustomizeconfig.yaml
  config/internal/fake-operator/default/manager_webhook_patch.yaml
  config/internal/fake-operator/default/webhookcainjection_patch.yaml
  config/internal/fake-operator/manager/manager.yaml
  config/internal/fake-operator/webhook/kustomization.yaml
  config/internal/fake-operator/webhook/kustomizeconfig.yaml
  config/internal/fake-operator/webhook/manifests.yaml
  config/internal/fake-operator/webhook/service.yaml
  hack/codegen.sh
  pkg/apis/fake/v1alpha1/db_types.go
  pkg/cli/internal/cmd/e2e-test/setup-e2e-operator.go
  pkg/fakeoperator/fakeoperator.go
  pkg/fakeoperator/internal/webhooks/controller_test.go
  pkg/fakeoperator/internal/webhooks/db_webhook.go
  pkg/fakeoperator/internal/webhooks/db_webhook_test.go
  pkg/internal/resources/fakeoperator/fakeoperator.golden.yaml
  pkg/internal/resources/fakeoperator/statik.go
  pkg/testutil/framework.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#382 Revert tower
  Makefile
  cmd/tower/main.go
  config/dockerfiles/tower.Dockerfile
  config/internal/tower/certmanager/certificate.yaml
  config/internal/tower/certmanager/kustomization.yaml
  config/internal/tower/certmanager/kustomizeconfig.yaml
  config/internal/tower/default/kustomization.yaml
  config/internal/tower/default/manager_webhook_patch.yaml
  config/internal/tower/default/webhookcainjection_patch.yaml
  config/internal/tower/manager/kustomization.yaml
  config/internal/tower/manager/manager.yaml
  config/internal/tower/prometheus/kustomization.yaml
  config/internal/tower/prometheus/monitor.yaml
  config/internal/tower/rbac/kustomization.yaml
  config/internal/tower/rbac/leader_election_role.yaml
  config/internal/tower/rbac/leader_election_role_binding.yaml
  config/internal/tower/rbac/role.yaml
  config/internal/tower/rbac/role_binding.yaml
  config/internal/tower/webhook/kustomization.yaml
  config/internal/tower/webhook/kustomizeconfig.yaml
  config/internal/tower/webhook/manifests.yaml
  config/internal/tower/webhook/service.yaml
  config/operator/crd/bases/operator.kubecarrier.io_towers.yaml
  config/operator/crd/kustomization.yaml
  config/operator/rbac/role.yaml
  docs/api_reference.md
  hack/codegen.sh
  hack/gen-tasks.go
  pkg/apis/operator/v1alpha1/tower_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/internal/resources/operator/operator.golden.yaml
  pkg/internal/resources/operator/statik.go
  pkg/internal/resources/tower/statik.go
  pkg/internal/resources/tower/tower.go
  pkg/internal/resources/tower/tower.golden.yaml
  pkg/internal/resources/tower/tower_test.go
  pkg/internal/resources/tower/z_init.go
  pkg/operator/internal/controllers/tower.go
  pkg/operator/operator.go
  pkg/tower/tower.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#392 Add an empty line between kubebuilder markers and function to make the rbac auto-generated
  pkg/fakeoperator/internal/controllers/db_controller.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#384 E2E operator conversion webhook
  config/internal/fake-operator/crd/bases/fake.kubecarrier.io_dbs.yaml
  config/internal/fake-operator/crd/kustomization.yaml
  config/internal/fake-operator/crd/kustomizeconfig.yaml
  config/internal/fake-operator/crd/patches/webhook_in_dbs.yaml
  pkg/apis/fake/v1/db_conversion.go
  pkg/apis/fake/v1/db_types.go
  pkg/apis/fake/v1/groupversion_info.go
  pkg/apis/fake/v1/types.go
  pkg/apis/fake/v1/zz_generated.deepcopy.go
  pkg/apis/fake/v1alpha1/db_conversion.go
  pkg/fakeoperator/fakeoperator.go
  pkg/internal/resources/fakeoperator/fakeoperator.golden.yaml
  pkg/internal/resources/fakeoperator/statik.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XL

#394 [Fake Operator] Upgrade webhook and controller for v1 DB.
  config/internal/fake-operator/webhook/manifests.yaml
  pkg/fakeoperator/fakeoperator.go
  pkg/fakeoperator/internal/controllers/db_controller.go
  pkg/fakeoperator/internal/webhooks/db_webhook.go
  pkg/fakeoperator/internal/webhooks/db_webhook_test.go
  pkg/internal/resources/fakeoperator/fakeoperator.golden.yaml
  pkg/internal/resources/fakeoperator/statik.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#395 Upgrade the controller-gen to 0.2.9
  config/dockerfiles/test.Dockerfile
  config/internal/fake-operator/crd/bases/fake.kubecarrier.io_dbs.yaml
  config/internal/manager/crd/bases/catalog.kubecarrier.io_accounts.yaml
  config/internal/manager/crd/bases/catalog.kubecarrier.io_catalogentries.yaml
  config/internal/manager/crd/bases/catalog.kubecarrier.io_catalogentrysets.yaml
  config/internal/manager/crd/bases/catalog.kubecarrier.io_catalogs.yaml
  config/internal/manager/crd/bases/catalog.kubecarrier.io_derivedcustomresources.yaml
  config/internal/manager/crd/bases/catalog.kubecarrier.io_offerings.yaml
  config/internal/manager/crd/bases/catalog.kubecarrier.io_providers.yaml
  config/internal/manager/crd/bases/catalog.kubecarrier.io_regions.yaml
  config/internal/manager/crd/bases/catalog.kubecarrier.io_tenants.yaml
  config/internal/manager/crd/bases/kubecarrier.io_customresourcediscoveries.yaml
  config/internal/manager/crd/bases/kubecarrier.io_customresourcediscoverysets.yaml
  config/internal/manager/crd/bases/kubecarrier.io_serviceclusterassignments.yaml
  config/internal/manager/crd/bases/kubecarrier.io_serviceclusters.yaml
  config/operator/crd/bases/operator.kubecarrier.io_catapults.yaml
  config/operator/crd/bases/operator.kubecarrier.io_elevators.yaml
  config/operator/crd/bases/operator.kubecarrier.io_ferries.yaml
  config/operator/crd/bases/operator.kubecarrier.io_kubecarriers.yaml
  hack/codegen.sh
  pkg/internal/resources/fakeoperator/fakeoperator.golden.yaml
  pkg/internal/resources/fakeoperator/statik.go
  pkg/internal/resources/manager/manager.golden.yaml
  pkg/internal/resources/manager/statik.go
  pkg/internal/resources/operator/operator.golden.yaml
  pkg/internal/resources/operator/statik.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#363 Operator Refactor
  pkg/operator/internal/controllers/base_controller.go
  pkg/operator/internal/controllers/catapult_controller.go
  pkg/operator/internal/controllers/elevator.go
  pkg/operator/internal/controllers/elevator_controller.go
  pkg/operator/internal/controllers/ferry.go
  pkg/operator/internal/controllers/ferry_controller.go
  pkg/operator/internal/controllers/kubecarrier_controller.go
  pkg/operator/internal/controllers/util.go
  pkg/operator/operator.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#393 Increase CI/CD resources
  .prow.yaml
  pkg/internal/util/clientwatcher.go
  pkg/testutil/framework.go
  test/integration/derivedcr.go
  test/integration/servicecluster.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S

#391 E2E helper CRDs
  config/internal/fake-operator/crd/bases/fake.kubecarrier.io_backups.yaml
  config/internal/fake-operator/crd/bases/fake.kubecarrier.io_snapshots.yaml
  config/internal/fake-operator/crd/kustomization.yaml
  config/internal/fake-operator/rbac/role.yaml
  pkg/apis/fake/v1/backup_type.go
  pkg/apis/fake/v1/snapshot_type.go
  pkg/apis/fake/v1/zz_generated.deepcopy.go
  pkg/fakeoperator/fakeoperator.go
  pkg/fakeoperator/internal/controllers/backup_controller.go
  pkg/fakeoperator/internal/controllers/snapshot_controller.go
  pkg/internal/resources/fakeoperator/fakeoperator.golden.yaml
  pkg/internal/resources/fakeoperator/statik.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XXL

#365 API server bootstrapping
  .goreleaser.yaml
  Makefile
  cmd/api-server/main.go
  config/dockerfiles/api-server.Dockerfile
  config/internal/api-server/certmanager/certificate.yaml
  config/internal/api-server/certmanager/kustomization.yaml
  config/internal/api-server/certmanager/kustomizeconfig.yaml
  config/internal/api-server/default/kustomization.yaml
  config/internal/api-server/default/manager_webhook_patch.yaml
  config/internal/api-server/default/webhookcainjection_patch.yaml
  config/internal/api-server/manager/kustomization.yaml
  config/internal/api-server/manager/manager.yaml
  config/internal/api-server/prometheus/kustomization.yaml
  config/internal/api-server/prometheus/monitor.yaml
  config/internal/api-server/rbac/kustomization.yaml
  config/internal/api-server/rbac/leader_election_role.yaml
  config/internal/api-server/rbac/leader_election_role_binding.yaml
  config/internal/api-server/rbac/role.yaml
  config/internal/api-server/rbac/role_binding.yaml
  config/internal/api-server/webhook/kustomization.yaml
  config/internal/api-server/webhook/kustomizeconfig.yaml
  config/internal/api-server/webhook/manifests.yaml
  config/internal/api-server/webhook/service.yaml
  config/operator/crd/bases/operator.kubecarrier.io_apiservers.yaml
  config/operator/crd/kustomization.yaml
  config/operator/rbac/role.yaml
  docs/api_reference.md
  hack/codegen.sh
  hack/gen-tasks.go
  pkg/api-server/apiserver.go
  pkg/apis/operator/v1alpha1/apiserver_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/internal/resources/api-server/api-server.golden.yaml
  pkg/internal/resources/api-server/apiserver.go
  pkg/internal/resources/api-server/apiserver_test.go
  pkg/internal/resources/api-server/statik.go
  pkg/internal/resources/api-server/z_init.go
  pkg/internal/resources/operator/operator.golden.yaml
  pkg/internal/resources/operator/statik.go
  pkg/operator/internal/controllers/apiserver_controller.go
  pkg/operator/operator.go
  test/integration/apiserver.go
  test/integration/integration.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/XXL

#387 Added protoc, helm & protoc-gen-* to test.dockerfile
  config/dockerfiles/test.Dockerfile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#396 Enable dryrun for e2e operator webhook
  config/internal/fake-operator/webhook/manifests.yaml
  pkg/fakeoperator/internal/webhooks/db_webhook.go
  pkg/internal/resources/fakeoperator/fakeoperator.golden.yaml
  pkg/internal/resources/fakeoperator/statik.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS
