Repository kubermatic/kubecarrier, pull requests merged in 2020-08, with the labels that each got.

#535 Add roadmap to readme
  README.md
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/M

#534 Use Ower handling from controller-runtime for Account
  pkg/manager/internal/controllers/account_controller.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/L

#536 Increase make generate performance on Mac by using delegated mount mode
  Makefile
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/XS

#544 Fix paused flag bugs
  pkg/apis/operator/v1alpha1/catapult_types.go
  pkg/apis/operator/v1alpha1/elevator_types.go
  pkg/apis/operator/v1alpha1/ferry_types.go
  pkg/apis/operator/v1alpha1/kubecarrier_types.go
  test/integration/derivedcr.go
  test/integration/servicecluster.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/M

#545 Add paused flag for API Server
  config/operator/crd/bases/operator.kubecarrier.io_apiservers.yaml
  config/operator/crd/bases/operator.kubecarrier.io_kubecarriers.yaml
  docs/api_reference/_index.md
  pkg/apis/operator/v1alpha1/apiserver_types.go
  pkg/internal/resources/operator/operator.golden.yaml
  pkg/internal/resources/operator/statik.go
  pkg/operator/internal/controllers/apiserver_controller.go
  pkg/operator/internal/controllers/kubecarrier_controller.go
  test/integration/apiserver.go
Labels: approved, dco-signoff: yes, lgtm, release-note, size/L

#550 check if status exists in management cluster object
  pkg/catapult/internal/controllers/managementclusterobj_controller.go
Labels: approved, dco-signoff: yes, lgtm, release-note-none, size/S
